replicaCount: 1

image:
  repository: nvcr.io/nvidia/tritonserver
  tag: 23.10-py3
  pullPolicy: IfNotPresent

modelRepository:
  hostPath: "/mnt/data/model_repository"
  mountPath: "/models"

resources:
  limits:
    nvidia.com/gpu: "1"
    memory: "2Gi"
  requests:
    nvidia.com/gpu: "1"
    memory: "1Gi"

service:
  type: ClusterIP
  httpPort: 8000
  grpcPort: 8001
  metricsPort: 8002