apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-low-priority
  namespace: default
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: low-priority
  ttlSecondsAfterFinished: 60
  tasks:
    - replicas: 4
      name: gpu-task
      template:
        spec:
          containers:
            - name: gpu-burn
              image: tensorflow/tensorflow:2.5.0-gpu
              command: ["python", "-c", "print('LOW priority job running'); import time; time.sleep(10)"]
              resources:
                limits:
                  nvidia.com/gpu: 1
          restartPolicy: Never