apiVersion: v1
kind: ServiceAccount
metadata:
  name: triton-gpu-checker
  namespace: triton

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triton-gpu-checker
rules:
  - apiGroups:
      - nvidia.com
    resources:
      - clusterpolicies
    verbs:
      - get

  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triton-gpu-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: triton-gpu-checker
subjects:
  - kind: ServiceAccount
    name: triton-gpu-checker
    namespace: triton